export default {
  "status":"0",
  "result":[
    {
        "productId":"10001",
        "productName":"小米6",
        "prodcutPrice":"2499",
        "prodcutImg":require("./imgs/mi6.jpg")
    },
    {
      "productId":"10002",
      "productName":"小米笔记本",
      "prodcutPrice":"3999",
      "prodcutImg":require("./imgs/note.jpg")
    },
    {
      "productId":"10003",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/mi6.jpg")
    },
    {
      "productId":"10004",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/1.jpg")
    },
    {
      "productId":"10005",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/2.jpg")
    },
    {
      "productId":"10006",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/3.jpg")
    },
    {
      "productId":"10007",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/4.jpg")
    },
    {
      "productId":"10008",
      "productName":"小米6",
      "prodcutPrice":"2499",
      "prodcutImg":require("./imgs/5.jpg")
    }
  ]
}
